# Site settings
title: Jason's GitHub Pages
email: jason.plojo@gmail.com
description:  This website has been generated for Live Blogging the RoboSub 2015 competition. It will eventually become a website featuring projects in the near future.
baseurl: "" # the subpath of your site, e.g. /blog/
github_username: jasonplojo
host: 192.168.1.104 

# Build settings
markdown: kramdown

# Include settings
include: ["_projects"]
